parlance/urls.py
# parlance.urls
# Defines all of the routes and associated views with the urls for the app.
#
# Author:   Benjamin Bengfort <benjamin@rotational.io>
# Created:  Tue Oct 01 21:19:17 2024 -0500
#
# Copyright (C) 2024 Rotational Labs, Inc.
# For license information, see LICENSE
#
# ID: urls.py [] benjamin@rotational.io $

"""
URL configuration for parlance project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

##########################################################################
## Imports
##########################################################################

from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from parley.views import ReviewTaskDetail
from parley.views import LLMList, LLMDetail
from parley.views import (
    EvaluationList,
    EvaluationDetail,
    EvaluationCreate,
    EvaluationDelete,
)
from parley.views import DownloadPrompts, DownloadAnalytics
from parlance.views import Dashboard, AccountSettings, AccountProfile
from parley.views import (
    UploaderFormView,
    CreateReviewTask,
    ResponseDetail,
    UpdateResponseReview,
)


##########################################################################
## URL Patterns
##########################################################################

urlpatterns = [
    # Application Pages
    path("", Dashboard.as_view(), name="dashboard"),
    path("upload/", UploaderFormView.as_view(), name="upload"),
    path("account/profile", AccountProfile.as_view(), name="account-profile"),
    path("account/settings", AccountSettings.as_view(), name="account-settings"),
    path("evaluations/", EvaluationList.as_view(), name="evaluations-list"),
    path("evaluations/create", EvaluationCreate.as_view(), name="evaluation-create"),
    path("evaluations/<uuid:pk>", EvaluationDetail.as_view(), name="evaluation-detail"),
    path(
        "evaluations/<uuid:pk>/download",
        DownloadPrompts.as_view(),
        name="evaluation-download",
    ),
    path(
        "evaluations/<uuid:pk>/analytics",
        DownloadAnalytics.as_view(),
        name="evaluation-analytics",
    ),
    path(
        "evaluations/<uuid:pk>/delete",
        EvaluationDelete.as_view(),
        name="evaluation-delete",
    ),
    path(
        "evaluations/create-review-task",
        CreateReviewTask.as_view(),
        name="create-review-task",
    ),
    path("reviews/<int:pk>", ReviewTaskDetail.as_view(), name="review-task"),
    path(
        "reviews/<int:pk>/update", UpdateResponseReview.as_view(), name="update-review"
    ),
    path("models/", LLMList.as_view(), name="llms-list"),
    path("models/<uuid:pk>", LLMDetail.as_view(), name="llm-detail"),
    path("responses/<uuid:pk>", ResponseDetail.as_view(), name="response-detail"),
    # Admin URLs
    path("admin/", admin.site.urls),
    # Authentication URLs
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    # Browser reload
    urlpatterns += [
        path("__reload__/", include("django_browser_reload.urls")),
    ]


##########################################################################
## Error handling
##########################################################################

handler400 = "parlance.views.bad_request"
handler403 = "parlance.views.permission_denied"
handler404 = "parlance.views.not_found"
handler500 = "parlance.views.server_error"

parley/models/base.py
# parley.models.base
# The abstract base model for all parley models.
#
# Author:   Benjamin Bengfort <benjamin@rotational.io>
# Created:  Sat Oct 05 15:11:26 2024 -0500
#
# Copyright (C) 2024 Rotational Labs, Inc.
# For license information, see LICENSE
#
# ID: base.py [] benjamin@rotational.io $

"""
The abstract base model for all parley models.
"""

##########################################################################
## Imports
##########################################################################

import uuid

from django.db import models


##########################################################################
## Base Model
##########################################################################


class BaseModel(models.Model):
    """
    In order to make it easier to ingest data and audit records added to parlance, the
    base model uses UUIDs as the primary key instead of sequences and adds timestamps
    to track modifications to all objects in the system.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        help_text="The globally unique identifier of the object",
    )

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        help_text="The timestamp that the object was created",
    )

    modified = models.DateTimeField(
        auto_now=True,
        editable=False,
        help_text="The timestamp that the object was last modified",
    )

    class Meta:
        abstract = True


class TimestampedModel(models.Model):
    """
    Adds created and modified timestamps to sub-models.
    """

    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        help_text="The timestamp that the object was created",
    )

    modified = models.DateTimeField(
        auto_now=True,
        editable=False,
        help_text="The timestamp that the object was last modified",
    )

    class Meta:
        abstract = True

parley/models/enums.py
# parley.models.enums
# Enum constants for use as model choices to simplify enum management.
#
# Author:   Benjamin Bengfort <benjamin@rotational.io>
# Created:  Sat Oct 05 15:45:20 2024 -0500
#
# Copyright (C) 2024 Rotational Labs, Inc.
# For license information, see LICENSE
#
# ID: enums.py [] benjamin@rotational.io $

"""
Enum constants for use as model choices to simplify enum management.
"""

##########################################################################
## Imports
##########################################################################

from django.db import models
from django.utils.translation import gettext_lazy as _


class SimilarityMetric(models.TextChoices):
    """
    Similarity metrics define the automated comparisons between an LLM response and the
    expected output as defined by the prompt.
    """

    COSINE_TFIDF = ("csti", _("Cosine TF-IDF"))
    COSINE_TF = ("cstf", _("Cosine Term Frequency"))
    JACCARD = ("jacc", _("Jaccard"))
    WORD2VEC = ("w2vc", _("Cosine of Word2Vec Average"))
    GLOVE = ("glve", _("Cosine of GloVe Average"))
    FAST = ("fast", _("Cosine of FastText Average"))
    DOC2VEC = ("d2vc", _("Cosine of Doc2Vec"))
    BERT = ("bert", _("Cosine of BERT"))


class OutputFormat(models.TextChoices):
    """
    OutputFormat indicates the expected serialized response from an LLM to a prompt.
    By default, this is usually just simple text, but LLMs and generative AI can also
    produce JSON, XML, CSV data or even images or data visualizations.
    """

    TEXT = ("text", _("text"))
    JSON = ("json", _("JSON"))
    XML = ("xml", _("XML"))
    CSV = ("csv", _("CSV"))
    IMAGE = ("img", _("image"))
    DATA_VIZ = ("dviz", _("Data Visualization"))


class FivePointLikert(models.IntegerChoices):
    """
    FivePointLikert is a standard 5-point Likert scale for user evaluations, where 1 is
    strongly disagree and 5 is strongly agree.
    """

    STRONGLY_DISAGREE = (1, _("Strongly Disagree"))
    DISAGREE = (2, _("Disagree"))
    NEUTRAL = (3, _("Neutral"))
    AGREE = (4, _("Agree"))
    STRONGLY_AGREE = (5, _("Strongly Agree"))

parley/models/evaluation.py
# parley.models.evaluation
# Evaluations and the prompts associated with those evaluations.
#
# Author:   Benjamin Bengfort <benjamin@rotational.io>
# Created:  Sat Oct 05 15:11:26 2024 -0500
#
# Copyright (C) 2024 Rotational Labs, Inc.
# For license information, see LICENSE
#
# ID: evaluation.py [] benjamin@rotational.io $

"""
The abstract base model for all parley models.
"""

##########################################################################
## Imports
##########################################################################

from django.db import models
from django.urls import reverse

from .base import BaseModel
from .enums import SimilarityMetric, OutputFormat


class Evaluation(BaseModel):
    """
    An Evaluation is a collection of related prompts that are used to perform a
    qualitative LLM evaluation. All of the prompts in the evaluation should be handled
    together, both when creating prompt outputs for a specific model and performing
    qualitative model evaluations.
    """

    name = models.CharField(
        default=None,
        null=False,
        blank=False,
        max_length=255,
        help_text="The descriptive name of the evaluation prompts collection",
    )

    task = models.CharField(
        default=None,
        null=False,
        blank=False,
        max_length=255,
        help_text="A description of the expected task or agent being evaluated",
    )

    description = models.TextField(
        null=True,
        blank=True,
        default=None,
        help_text="Any notes or other descriptive information about the evaluation",
    )

    similarity_metric = models.CharField(
        null=False,
        max_length=4,
        choices=SimilarityMetric,
        default=SimilarityMetric.COSINE_TFIDF,
        help_text="The similarity metric used to compare output to expected output",
    )

    similarity_threshold = models.FloatField(
        default=0.5,
        help_text="The similarity threshold to determine if an output is generally correct or not",
    )

    active = models.BooleanField(
        default=True,
        null=False,
        help_text="This prompt set should be used in evaluations of new models",
    )

    llms = models.ManyToManyField(
        "parley.LLM",
        through="parley.ModelEvaluation",
    )

    class Meta:
        db_table = "evaluations"
        ordering = ("-created",)
        get_latest_by = "created"
        verbose_name = "evaluation"
        verbose_name_plural = "evaluations"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("evaluation-detail", args=(self.id,))


class Prompt(BaseModel):
    """
    A prompt is a single instance of an input to an LLM.
    """

    title = models.CharField(
        null=True, default=None, blank=True,
        help_text="A title to specify for identifying the prompt",
    )

    system = models.TextField(
        null=True,
        default=None,
        blank=True,
        help_text="The system prompt specified to the LLM",
    )

    prompt = models.TextField(
        null=False,
        default=None,
        blank=False,
        help_text="The prompt used to generate an output from an LLM",
    )

    evaluation = models.ForeignKey(
        "parley.Evaluation",
        null=False,
        on_delete=models.CASCADE,
        related_name="prompts",
        help_text="The evaluation that this prompt is a part of",
    )

    history = models.JSONField(
        null=True,
        default=None,
        blank=True,
        help_text="An array of prompt IDs that precede this prompt during evaluation",
    )

    notes = models.TextField(
        null=True,
        blank=True,
        default=None,
        help_text="Any notes or other descriptive information about the prompt",
    )

    expected_output_type = models.CharField(
        max_length=4,
        choices=OutputFormat,
        default=OutputFormat.TEXT,
        help_text="Specify the expected type of output for the prompt to validate",
    )

    expected_output = models.TextField(
        null=True,
        blank=True,
        default=None,
        help_text="Expected output for the prompt to use similarity scoring with",
    )

    expected_label = models.CharField(
        null=True,
        blank=True,
        default=None,
        max_length=255,
        help_text="For classifiers, expected label that should be contained in output",
    )

    order = models.IntegerField(
        null=True,
        blank=True,
        default=None,
        help_text="Manually specify the order of the prompts for review",
    )

    exclude = models.BooleanField(
        default=False,
        help_text="Exclude this prompt from evaluations and from metrics",
    )

    class Meta:
        db_table = "prompts"
        ordering = ("evaluation__id", "order", "-created")
        get_latest_by = "created"
        verbose_name = "prompt"
        verbose_name_plural = "prompts"

    def __str__(self):
        if self.title:
            return self.title

        if self.order:
            return f"{self.evaluation.name} Prompt #{self.order}"

        return f"{self.evaluation.name} ({self.id})"

    def get_absolute_url(self):
        return reverse("prompt-detail", args=(self.id,))

parley/models/sensitive.py
# parley.models.sensitive
# Handling of sensitive data and validation.
#
# Author:   Benjamin Bengfort <benjamin@rotational.io>
# Created:  Sat Oct 05 15:11:26 2024 -0500
#
# Copyright (C) 2024 Rotational Labs, Inc.
# For license information, see LICENSE
#
# ID: llm.py [] benjamin@rotational.io $

"""
Handling of sensitive data and validation.
"""

##########################################################################
## Imports
##########################################################################

import re

from django.db import models
from .base import TimestampedModel


class Sensitive(TimestampedModel):
    """
    Any data or information that should be considered sensitive and not included
    in any output across any evaluation. These can be specific strings or they can
    be regular expressions to search the output for.
    """

    term = models.CharField(
        blank=False,
        null=False,
        max_length=255,
        unique=True,
        help_text="The search term to look for sensitive data in output",
    )

    is_regex = models.BooleanField(
        null=False,
        default=False,
        help_text="If the term is a regular expression to analyze the output on",
    )

    is_name = models.BooleanField(
        null=False,
        default=False,
        help_text="If the term is a proper name that may be extracted and fuzzy searched with NER",
    )

    case_sensitive = models.BooleanField(
        null=False,
        default=False,
        help_text="Do not use case insensitive search to locate the sensitive term",
    )

    class Meta:
        db_table = "sensitive"
        ordering = ("-created",)
        get_latest_by = "created"
        verbose_name = "sensitive"
        verbose_name_plural = "sensitive"

    def search(self, text: str) -> bool:
        if self.is_regex:
            args = [self.term, text]
            if not self.case_sensitive:
                args.append(re.IGNORECASE)

            if re.search(*args):
                return True
            return False

        if not self.case_sensitive:
            text = text.casefold()
            term = self.term.casefold()
        else:
            term = self.term

        return text.find(term) > -1

    def __str__(self):
        return self.term

parley/templates/evaluation/detail.html
{% extends 'page.html' %}
{% load parlance %}

{% block page-pretitle %}Evaluations{% endblock %}
{% block page-title %}{{ evaluation.name }}{% endblock %}
{% block page-controls %}
  {% if user.is_staff %}
  <a href="{% url 'admin:parley_evaluation_change' evaluation.pk %}" class="btn btn-primary" title="Edit Evaluation">
    <span class="fe fe-edit"></span>
  </a>
  {% endif %}
  <a href="{% url 'evaluation-analytics' evaluation.pk %}" class="btn btn-info" title="Download CSV for Analytics">
    <span class="fe fe-download-cloud"></span>
  </a>
  <a href="{% url 'evaluation-download' evaluation.pk %}" class="btn btn-secondary" title="Download Prompts">
    <span class="fe fe-download"></span>
  </a>
{% endblock %}

{% block page %}
  <!-- evaluation information -->
  <div class="row">
    <div class="col-12">

      <div class="card">
        <div class="card-body">
          {% if evaluation.task %}
          <p class="lead">{{ evaluation.task }}</p>
          {% endif %}
          <div class="info-pills">
            <span class="badge text-bg-primary py-2">{{ evaluation.prompts.count }} prompts</span>
            <span class="badge text-bg-info py-2">{{ evaluation.get_similarity_metric_display }} (t={{ evaluation.similarity_threshold }})</span>
            {% with n_models=evaluation.llms.count %}
            <span class="badge py-2 {% if n_models == 0 %}text-bg-danger{% else %}text-bg-info{% endif %}">{{ n_models }} models</span>
            {% endwith %}
          </div>
          {% if evaluation.description %}
          <div class="description">
          {{ evaluation.description|linebreaks }}
          </div>
          {% endif %}
        </div>
      </div>

    </div>
  </div><!-- evaluation information ends -->


  <!-- model info list -->
  <div class="row">
    <div class="col-12">

      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">Models under Evaluation</h4>
        </div>

        <div class="card-body">
          <ul class="list-group list-group-lg list-group-flush list my-n4">
            {% for model in evaluation.model_evaluations.all %}
            <li class="list-group-item">
              <div class="row align-items-center">
                <div class="col-auto">
                  <!-- icon -->
                  <a href="#!" class="avatar avatar-lg">
                    <span class="avatar-title rounded bg-white text-secondary">
                      <span class="fe fe-cpu"></span>
                    </span>
                  </a>
                </div>
                <div class="col ms-n2">
                  <h4 class="mb-1 name">
                    <a href="{{ model.model.get_absolute_url }}">{{ model.model.name }} <span class="badge text-bg-light">v{{ model.model.version }}</span></a>
                  </h4>

                  <p class="card-text small text-muted mb-1">
                    {{ model.percent_complete }}% responses completed for evaluation
                  </p>

                </div>
                <div class="col-auto">
                  {% with n_reviewers=model.reviewers.count %}
                  <span class="badge py-2 {% if n_reviewers == 0 %}text-bg-danger{% elif n_reviewers < 3 %}text-bg-warning{% else %}text-bg-info{% endif %}">{{ n_reviewers }} reviewers</span>
                  {% endwith %}

                  {% get_review_task user model as review_task %}
                  {% if review_task %}
                  {% if review_task.is_completed %}
                  <span class="badge py-2 text-bg-success">Review Complete!</span>
                  {% else %}
                  <a href="{{ review_task.get_absolute_url }}" class="btn btn-sm btn-white d-none d-xl-inline-block">
                    Continue Review
                  </a>
                  {% endif %}
                  {% else %}
                  <form action="{% url 'create-review-task' %}" method="post" class="m-0 p-0 d-inline-block">
                    <input type="hidden" name="user" value="{{ user.id }}" />
                    <input type="hidden" name="evaluation" value="{{ model.id }}" />
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-dark d-none d-xl-inline-block">
                      Begin Review
                    </button>
                  </form>
                  {% endif %}
                </div>
                <div class="col-auto">

                  <!-- Dropdown -->
                  <div class="dropdown">
                    <a href="#" class="dropdown-ellipses dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fe fe-more-vertical"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                      {% if user.is_staff %}
                      <a href="{% url 'admin:parley_modelevaluation_change' model.pk %}" class="dropdown-item">
                        Edit in CMS
                      </a>
                      {% endif %}
                      <a href="{% url 'llm-detail' model.model.pk %}" class="dropdown-item">
                        View Model
                      </a>
                    </div>
                  </div>

              </div>
              </div>
            </li>
            {% empty %}
            <li class="list-group-item">
              <p>No Models Yet!</p>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>

    </div>
  </div><!-- model info list ends -->
  <!-- model evaluation metrics -->
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">Normalized Metrics</h4>
        </div>
        <div class="chart">
          <canvas id="metricsChart" class="chart-canvas"></canvas>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">Boolean Metrics</h4>
        </div>
        <div class="table-responsive mb-0">
          <table class="table table-sm table-nowrap card-table">
            <thead>
              <tr>
                <th>Evaluation</th>
                <th>Metric</th>
                <th class="text-center">Positive</th>
                <th class="text-center">Negative</th>
              </tr>
            </thead>
            <tbody>
              {% for eval in evaluation.model_evaluations.all %}
              {% if eval.metrics_cached %}
              {% if eval.valid_output_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Valid Output</td>
                <td class="text-center">{{ eval.n_valid_output_type }} ({{ eval.percent_valid_output_type }}%)</td>
                <td class="text-center">{{ eval.n_invalid_output_type }} ({{ eval.percent_invalid_output_type }}%)</td>
              </tr>
              {% endif %}
              {% if eval.sensitive_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Leaks Sensitive</td>
                <td class="text-center">{{ eval.n_leaks_sensitive }} ({{ eval.percent_leaks_sensitive }}%)</td>
                <td class="text-center">{{ eval.n_no_sensitive_leaks }} ({{ eval.percent_no_sensitive_leaks }}%)</td>
              </tr>
              {% endif %}
              {% if eval.similarity_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Similarity to Expected</td>
                <td class="text-center">{{ eval.n_similar }} ({{ eval.percent_similar }}%)</td>
                <td class="text-center">{{ eval.n_not_similar }} ({{ eval.percent_not_similar }}%)</td>
              </tr>
              {% endif %}
              {% if eval.labels_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Labeled Correctly</td>
                <td class="text-center">{{ eval.n_labeled_correctly }} ({{ eval.percent_labeled_correctly }}%)</td>
                <td class="text-center">{{ eval.n_labeled_incorrectly }} ({{ eval.percent_labeled_incorrectly }}%)</td>
              </tr>
              {% endif %}
              {% if eval.factual_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Is Factual</td>
                <td class="text-center">{{ eval.n_factual }} ({{ eval.percent_factual }}%)</td>
                <td class="text-center">{{ eval.n_not_factual }} ({{ eval.percent_not_factual }}%)</td>
              </tr>
              {% endif %}
              {% if eval.readability_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Readable Output</td>
                <td class="text-center">{{ eval.n_readable }} ({{ eval.percent_readable }}%)</td>
                <td class="text-center">{{ eval.n_not_readable }} ({{ eval.percent_not_readable }}%)</td>
              </tr>
              {% endif %}
              {% endif %}
              {% if eval.style_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Is Correct Style</td>
                <td class="text-center">{{ eval.n_correct_style }} ({{ eval.percent_correct_style }}%)</td>
                <td class="text-center">{{ eval.n_incorrect_style }} ({{ eval.percent_incorrect_style }}%)</td>
              </tr>
              {% endif %}
              {% empty %}
              <tr>
                <td colspan="4">No Evaluations Run</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          <h4 class="card-header-title">Scalar Metrics</h4>
        </div>
        <div class="table-responsive mb-0">
          <table class="table table-sm table-nowrap card-table">
            <thead>
              <tr>
                <th>Evaluation</th>
                <th>Metric</th>
                <th class="text-center">Mean</th>
                <th class="text-center">Median</th>
                <th class="text-center">Total</th>
              </tr>
            </thead>
            <tbody>
              {% for eval in evaluation.model_evaluations.all %}
              {% if eval.metrics_cached %}
              {% if eval.helpfulness_processed %}
              <tr>
                <td>{{ eval.model.name }}</td>
                <td>Helpfulness</td>
                <td class="text-center">{{ eval.mean_helpfulness|floatformat:2 }}</td>
                <td class="text-center">{{ eval.median_helpfulness|floatformat:2 }}</td>
                <td class="text-center">{{ eval.n_responses }}</td>
              </tr>
              {% endif %}
              {% endif %}
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div><!-- model evaluation metrics ends -->
{% endblock %}

{% block javascripts %}
  {{ block.super }}
  <script>
    new Chart('metricsChart', {
      type: 'bar',
      options: {
        indexAxis: 'y',  // Make bars horizontal
        barThickness: 24,
        plugins: {
          legend: {
            display: true,
            position: 'top',
            labels: {
              boxWidth: 12,
              padding: 20
            }
          },
          tooltip: {
            mode: 'y',
            position: 'nearest',
            callbacks: {
              label: function(context) {
                const model = context.dataset.label;
                const value = context.dataset.trueValues[context.dataIndex];
                return `${model}: ${value}`;
              }
            }
          }
        },
        scales: {
          x: {
            stacked: true,
            min: 0,
            max: 1,
          },
          y: {
            stacked: true
          }
        }
      },
      data: {
        labels: {{ chart.labels|safe }},
        datasets: {{ chart.datasets|safe }}
      }
    });
  </script>
{% endblock %}